export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const ACCOUNT_UPDATED = 'ACCOUNT_UPDATED';
export const GET_FACILITIES = 'GET_FACILITIES';
export const GET_FACILITY = 'GET_FACILITY';
export const FACILITY_ERROR = 'FACILITY_ERROR';
export const FACILITIES_ERROR = 'FACILITIES_ERROR';
export const CLEAR_FACILITIES = 'CLEAR_FACILITIES';
export const CREATE_FACILITIES = 'CREATE_FACILITIES';
export const DELETE_FACILITY = 'DELETE_FACILITY';
export const MENUS_ERROR = 'MENUS_ERROR';

export const CLEAR_MENUS = 'CLEAR_MENUS';
export const CREATE_MENUS = 'CREATE_MENUS';
export const GET_MENUS = 'GET_MENUS';
export const GET_MENU = 'GET_MENU';
export const DELETE_MENU = 'DELETE_MENU';

export const CREATE_CONNECTION_RESTAURANT_MENU =
  'CREATE_CONNECTION_RESTAURANT_MENU';
export const DELETE_CONNECTION_RESTAURANT_MENU =
  'DELETE_CONNECTION_RESTAURANT_MENU';
export const GET_CONNECTION_RESTAURANT_MENU = 'GET_CONNECTION_RESTAURANT_MENU';
export const ERROR_CONNECTION_RESTAURANT_MENU =
  'ERROR_CONNECTION_RESTAURANT_MENU';
export const CLEAR_CONNECTION_RESTAURANT_MENU =
  'CLEAR_CONNECTION_RESTAURANT_MENU';

export const CREATE_DISHES = 'CREATE_DISHES';
export const GET_DISHES = 'GET_DISHES_BY_MENU';
export const GET_DISHES_BY_RESTAURANT = 'GET_DISHES_BY_RESTAURANT';
export const GET_DISH = 'GET_DISH';
export const DELETE_DISH = 'DELETE_DISHES';
export const UPDATE_DISH = 'UPDATE_DISH';
export const CLEAR_DISHES = 'CLEAR_DISHES';
export const ERROR_DISHES = 'ERROR_DISHES';
export const GET_CURRENCIES = 'GET_CURRENCIES';

export const CREATE_SELLING_REPORT = 'CREATE_SELLING_REPORT';
export const UPDATE_ITEM_FROM_SELLING_REPORT = 'UPDATE_ITEM_FROM_SELLING_REPORT';
export const DELETE_SELLING_REPORT = 'DELETE_ITEM_FROM_SELLING_REPORT';
export const GET_SELLING_REPORT_BY_DATE = 'GET_SELLING_REPORT_BY_DATE';
export const ERROR_SELLING_REPORT = 'ERROR_SELLING_REPORT';

export const TOGGLE_SORT = 'TOGGLE_SORT';

export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const CREATE_PRODUCTS = "CREATE_PRODUCTS"
export const GET_PRODUCTS = "GET_PRODUCTS"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const ERROR_PRODUCT = "ERROR_PRODUCT"
export const GET_PRODUCT = "GET_PRODUCT"

export const GET_STOCK_REPORT_BY_DATE = "GET_STOCK_REPORT_BY_DATE"
export const CREATE_STOCK_REPORT = "CREATE_STOCK_REPORT"
export const DELETE_STOCK_REPORT = "DELETE_STOCK_REPORT"
export const UPDATE_ITEM_FROM_STOCK_REPORT = "UPDATE_ITEM_FROM_STOCK_REPORT"
export const ERROR_STOCK_REPORT = "ERROR_STOCK_REPORT"